name: Generate PDF

on:
  push:
    branches:
      - main  # Modify this to match your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex

    - name: Generate PDF
      run: |
        pandoc -s menuscript.md -o menuscript.pdf
      working-directory: ./

    - name: Upload PDF Artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-pdf
        path: ./menuscript.pdf


    - name: Move PDF to gh-pages Branch
      run: |
        git config --global user.email "rraffiu@gmail.com"
        git config --global user.name "Rafi Ullah"
        mkdir -p pdf
        mv menuscript.pdf pdf/
        git checkout -b gh-pages
        git add pdf/
        git commit -m "Add PDF to gh-pages"
        git remote set-url origin "https://github.com/${{ github.repository }}.git"
        git push --force origin gh-pages
      working-directory: ./
      env:
        PDF_GH_PAGES: ${{ secrets.PDF_GH_PAGES }}
